### ISSUE TITLE
Version number (Mod version:)

### ISSUE THREAD

**Issue by Galixte** [alg5/liveSearch#12]
Hi @alg5,

in ACP since your commit here: https://github.com/alg5/liveSearch/commit/c58b0942860c0c9c3e5769da0df3c035c094c10f the version number (Mod version:) isn’t displayed.

Futhermore, the text “Mod version:” should be in english “Extension version:”.

**Comment by alg5** [comment]
see https://github.com/alg5/liveSearch/commit/c58b0942860c0c9c3e5769da0df3c035c094c10f

**Comment by Galixte** [comment]
Ok i will close this issue when your commit will be submitted.

**Comment by alg5** [comment]
see new version

**Comment by Galixte** [comment]
I will test now, maybe you should remove this language key too ```ACP_LIVE_SEARCH_MOD_VER```.

**Comment by alg5** [comment]
no problem

**Comment by alg5** [comment]
but my lang file was updated now, I am working on the next version and this key we be remove in the future

**Comment by alg5** [comment]
Please, test it. I this version ok I could to post it in the phpbb.com/community

**Comment by Galixte** [comment]
OK right now

**Comment by Galixte** [comment]
Mod/extension version isn’t displayed, it’s OK but i found an error, i will post a new issue, now.

**Comment by alg5** [comment]
I deleted ACP_LIVE_SEARCH_MOD_VER from english pack

**Comment by Galixte** [comment]
Ok, but why don’t remove from RU and FR languages ? Please remove those.

**Comment by alg5** [comment]
please. remove from FR. I'll remove from RU in the next version

**Comment by Galixte** [comment]
Done here: https://github.com/alg5/liveSearch/pull/16.
