### ISSUE TITLE
Jabber link doesn’t work

### ISSUE THREAD

**Issue by Galixte** [alg5/liveSearch#14]
Hi @alg5,

if i click on username by this extension, it will be displayed all link from mini profilte, internet website, PM, email, etc… and Jabber.

If i click on Jabber link it doesn’t work, a popup is displayed with this adress: ```http://www.domain.tld/%7Dmemberlist.php?mode=contact&action=jabber&u=2``` and the error message is:
```
Information

No route found for "GET /%7Dmemberlist.php"
```

The correct adress should be: ```http://www.domain.tld/memberlist.php?mode=contact&action=jabber&u=2```.

**Comment by alg5** [comment]
How to attach jabber? I didn't find option in the ucp and in db tables. may be jabber excludes from phpbb?

**Comment by Galixte** [comment]
On my board Jabber works perfectly.

First you have to configure a jabber server in ACP, secondly you have to enter a jabber contact in your UCP.

I wrote a user guide here: http://www.ezcom-fr.com/viewtopic.php?f=23&t=278 (Quick language is activated, and the drop menu “translate to” is below my Guide message).

**Comment by alg5** [comment]
Hi @Galixte, may be you post data for jabber from the table phpbb_profile_fields It's enouth and  will be more soon to fix this bug

**Comment by Galixte** [comment]
I think the answer is this: http://stackoverflow.com/questions/22510329/what-do-the-chars-7d-mean-in-an-url-query, “%7D is the ASCII code for the } character, which is probably leaking through from a template...”

**Comment by alg5** [comment]
ok, it's really no data in phpbb_profile_fields tables, there is a field user jabber in phpbb_users. What's data in this field?

**Comment by alg5** [comment]
"I think the answer is this" I'm not sure. I compared url for e-mail and url for jabber and other url connected with memberlist. I'd not found difference

**Comment by Galixte** [comment]
“ok, it's really no data in phpbb_profile_fields tables, there is a field user jabber in phpbb_users. What's data in this field?”, in phpbb_users there is a user_jabber field, in that there is my email contact for jabber service, like this: galixte@jabber.fr by example.

**Comment by Galixte** [comment]
FIxed here: https://github.com/alg5/liveSearch/pull/15.

**Comment by Galixte** [comment]
And here: https://github.com/alg5/liveSearch/pull/17.
