### ISSUE TITLE
“Turn on the quick search of similar topics” option

### ISSUE THREAD

**Issue by Galixte** [alg5/liveSearch#18]
Hi @alg5,

when i use this style https://github.com/inventea/we_universal and when i want to post a new topic, the field: “Subject:” is very small, code source indicated this:
```
<input type="text" name="subject" id="subject" size="45" maxlength="120" tabindex="2" value="" class="inputbox autowidth acInput" autocomplete="off" style="padding-left: 2px;"> 
```
while when this option is disabled the code source indicated this:
```
<input type="text" name="subject" id="subject" size="45" maxlength="120" tabindex="2" value="" class="inputbox autowidth">
```

However, i think this option is very very useless, why search a topic in this place while there is the same choice in top of forum with the Live search from this extension ?

**Comment by alg5** [comment]
@Galixte, it was a request from users to add a quick search when creating a new topic. Its meaning is not to find and go (as above), but when you create a new topic immediately see similar topics by title. As in the extension "similar topics"

**Comment by Galixte** [comment]
Ok i understand but, what can you do to fix this issue ?

**Comment by alg5** [comment]
the class "acInput"  and attribute autocomplete="off" this extension adds to the input
I don't see issue

**Comment by Galixte** [comment]
When this option is activated in prosilver there is this code:
```
<input type="text" name="subject" id="subject" size="45" maxlength="120" tabindex="2" value="" class="inputbox autowidth acInput" autocomplete="off" style="padding-left: 2px;">
```
and the field: “Subject:” is normal, while on We_universal style this field is very small.


in jquery.autocomplete.css, there is:
```
.acInput {
      	width: 125px;
      	background-color: #FFFFFF;
      	border: 1px solid #c0c0c0 !important;
      	color: #333333;
      	padding: 2px 2px 2px 17px;
      	cursor: text;
      	color: #999999;
      	background-position: 0 center;
      	height: 15px;
      	font-family: Verdana,Helvetica,Arial,sans-serif !important;
      	font-size: 10px !important;
}
```
and if remove the line:
```
      	height: 15px;
```
this field is correctly displayed on We_universal style.

this is the part of “forms.css” file which is concerned:
```
select,
.inputbox {
	box-sizing: border-box;
	box-shadow: inset 0 7px 5px -6px #e1e1e1;
	height: 28px;
	padding: 4px 6px;
	color: #525252;
}
```espacially this line:  ```	height: 28px;```.

**Comment by alg5** [comment]
@Galixte,  you may create folder styles/We_universal/theme and set css-rules especially for this style

**Comment by Galixte** [comment]
OK PR here: https://github.com/alg5/liveSearch/issues/19
