### ISSUE TITLE
Please update the French translation file

### ISSUE THREAD

**Issue by sslorigin** [alg5/liveSearch#29]
Hi @alg5 

There are some errors in the French translation file

![Capture d’écran 2020-11-17 à 16 47 29](https://user-images.githubusercontent.com/69965579/99414168-d9701800-28f6-11eb-8477-abb2d82bbabc.png)

Here after fixes

![Capture d’écran 2020-11-17 à 16 58 03](https://user-images.githubusercontent.com/69965579/99414376-091f2000-28f7-11eb-9cc5-c16b582852c5.png)

The corrected French language file

[fr.zip](https://github.com/alg5/liveSearch/files/5554666/fr.zip)

Best regards

**Comment by alg5** [comment]
Hi Fred! it's done. A lot of thanks
