### ISSUE TITLE
Can't read the english language files

### ISSUE THREAD

**Issue by Galixte** [alg5/liveSearch#3]
Hi,

i want to translate this extension in French but the english language files are not readable.

**Comment by alg5** [comment]
Hi. Galixte, I'll do it as soon as I can

**Comment by alg5** [comment]
Translate to English done, ext works, but I have trouble with  travis validation

**Comment by Galixte** [comment]
OK,

i will make the French translation, thanks !

**Comment by Galixte** [comment]
Hi @alg5,

it's done and i had many issues but only one is not fixed, could you take a look ?

**Comment by alg5** [comment]
yes sure,  but not now
thanks a lot
