### ISSUE TITLE
Send private message & Send email doesn't work

### ISSUE THREAD

**Issue by Galixte** [alg5/liveSearch#8]
Hi,

on the board when i search a user with liveSearch extension. It's displayed the profile links and the search links for topics/messages in the board/forum/topic "Send private message" & "Send email" don't work:
- "Send private message" link is under the form: ```http://www.domain.tld/ucp.php?i=pm&mode=compose&u2``` instead of ```http://www.domain.tld/ucp.php?i=pm&mode=compose&u=2``` FIXED HERE: https://github.com/alg5/liveSearch/pull/9
- "Send email" link is under the form: ```mailto:2``` instead of ```mailto:user@domain.tld``` FIXED here: https://github.com/alg5/liveSearch/commit/0655ac45ea4863fa8a7be3523c0d4d28376cc40f

**Comment by alg5** [comment]
fixed

**Comment by Galixte** [comment]
Yes thanks !-)
